### ISSUE TITLE
Doorbell ring action

### ISSUE THREAD

**Issue by kapps7** [homespun/homebridge-platform-ring-video-doorbell#10]
Hi, thanks for the plugin.
Can you pls explain what the options mean. Also, is it possible to include when the doorbell rings ?
Thanks

**Comment by mrose17** [comment]
- `ttl` is the polling interval (in seconds)

- `verboseP` determines whether the pluging should log verbosely

in general, you shouldn't need to change either of these options (and since they are the defaults, you can leave them out of your `config.json` file).

the plugin will report ringing to homekit, but only if it happens to catch that during a poll. the ring app has a better way of getting notifications than polling, but that api isn't available to the plugin...

**Comment by kapps7** [comment]
Thanks for that. I assume they also haven't made the Live View api available.

**Comment by mrose17** [comment]
cf., https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/6#issuecomment-284774326 ... there's a SIP URL, but i'm looking for a volunteer to do the work...
