### ISSUE TITLE
Confirm functionality

### ISSUE THREAD

**Issue by kieranmjones** [homespun/homebridge-platform-ring-video-doorbell#3]
I have just got this working and I just want to clarify functionality, I see I have a motion sensor device which works perfectly. Should there also be an actual doorbell device in HomeKit, I was expecting/hoping for a button pushed event to do some smarts on with other HomeKit devices.

Thank you by the way, this is a great bit of work and just what i was looking for!

**Comment by mrose17** [comment]
@kieranmjones - thanks for checking. you're correct (as of now).

the homekit definition of a doorbell service is "interesting" ... a programmable switch event (indicating a push) and then brightness and volume. i haven't been able to find a homekit client (not even [elgato eve](https://www.elgato.com/en/eve). so, what that means is that having the motion sensor service is sufficient.

keeping that in mind, i may be able to figure out how to add a camera control service, which is the "big ask" on this project!

your thoughts?

**Comment by kieranmjones** [comment]
Thanks for the feedback, I think the camera could be a very big ask indeed. From what I understand about the Ring when the button is pushed it initiates a SIP session and a video RTSP stream, if you're able to get that streak information for the Ring web service then I guess you should be able to spin up ffmpeg to convert it to a format HomeKit understands, check out the ffmpeg homebridge module for an example of this.

Currently the motion sensing is working great, it would be good to have that button push even though even without a camera. 

The impressive thing about HomeKit is that as I have a camera on my driveway anyway when the Ring senses motion, HomeKit sends me a push notification along with a snapshot from the CCTV camera anyway, it did that on its own with no config, I guess it just knows they're in the same area. 

I'll see if I can dig out that blog I found about precisely how the Ring call works with video stream etc.

In the mean time I would love to get the push event into HomeKit, would be super useful. Let me know if I can help with anything.

**Comment by mrose17** [comment]
i agree... since the motion detection works well, the doorbell service isn't really needed.

by "push event" are you referring to an ffmpeg stream or something else?

**Comment by mrose17** [comment]
@kieranmjones - check out the second paragraph of https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera#homekit-integrations ... this is where the magic is coming from!

**Comment by kieranmjones** [comment]
By push event I mean when someone actually pushes the button, at the moment the only accessory in HomeKit is the motion sensor for when ring detects motion, I'd love to have another for the actual doorbell button being pushed, assuming such a concept exists in HomeKit which I assume it does.

Camera integration in HomeKit is awesome, it would be amazing if you can make that work! Here is the blog I was talking about, it's for doorbot but I presume a lot of the back end is the same http://www.prism19.com/doorbot/

**Comment by mrose17** [comment]
@kieranmjones - i see now. the issue, i think is that i can't find a homekit app that actually supports doorbells -- @KhaosT and @florian-muc, any pointers to one?

in the short term, we could make the push sensor a motion sensor that automatically turns off after 10 seconds. would that work?

**Comment by KhaosT** [comment]
The doorbell support for HomeKit is built into iOS. You don't need an app for that. After pairing with accessory that supports doorbell service, iOS will handle the notification automatically and show the snapshot from IP Camera if there is one.

**Comment by mrose17** [comment]
interesting. ok, let me add it and see what's what... thanks for the tip!

**Comment by KhaosT** [comment]
to try it out, I'd suggest you use HomeKit Accessory Simulator since it provides both camera and doorbell.

**Comment by mrose17** [comment]
heh, heh. it turns out that the code has been there all along:

- https://github.com/homespun/homebridge-platform-ring-video-doorbell/blob/master/index.js#L318-L331
- https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L230-L237
- https://github.com/homespun/homespun-discovery/blob/master/utilities/utility-pushsensor.js#L373-L376

i thought i had disabled it, but it's been running all along.  so, time for me to check the logs and see if it's working right!

sorry for the confusion...

**Comment by kieranmjones** [comment]
Great! Good to see the code is there, now as you say to work out if it's working, or even what it's meant to do I suppose. One would expect the doorbell push event would at the very least be available in the "Automation" but of the Home app in order to programme events on doorbell push like turning a light on. Plus I would expect a notification through the Home app on push... I shall await the results of your tests!

Let me know if I can help with anything.

**Comment by mrose17** [comment]
you can define a rule-based scene with
- [elgato eve](https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8)
- [Hesperus](https://itunes.apple.com/us/app/hesperus/id969348892?mt=8)
- [Home Dash](https://itunes.apple.com/us/app/homedash-home-automation-homekit/id1003033186?mt=8)
- [Looming](https://itunes.apple.com/us/app/looming-easy-home-automation/id1098415311?mt=8)

elgato eve doesn't know about doorbells, and won't show the `ProgrammableSwitchEvent` as displayable (e.g., under Rooms), but you an select it as a "value trigger".

hesperus does a nice job of showing the device and the scene, even if it doesn't know that we're talking about a door bell

home dash also doesn't know about doorbells, but calls it a battery (because it does know about the battery service)

looming also is able to display/create a trigger for the `ProgrammableSwitchEvent` even though it doesn't know it's dealing with a doorbell

i think you can define a characteristic trigger using the HMCatalog App (characteristic event: programmable switch event -> on)

the apple home app will crash whenever you try to create a trigger with it (and it won't show the programmable switch event)

hestia reports "Some characteristics are unreadable" when you go to look at the programmable switch event, and it's not possible to create a input event

the ezzi home app won't show the programmable switch event characteristic

ditto for the home cat app

ditto for the iDevices app

**Comment by VeniceNerd** [comment]
@kieranmjones What IP camera do you have set up that supports HomeKit already? I wasn't even aware there are any released yet? Would love to hear your setup!

**Comment by kieranmjones** [comment]
@venicenerd Good question, I am actually using some generic cameras from China somewhere, Huacam I believe. They don't support HomeKit but I use Homebridge-ffmpeg on a home server (that also runs my ZoneMinder) to make them HomeKit capable. It's a bit of a poor experience but that is down to ffmpeg doing a bad job of converting streams to something the HomeKit software supports, a native HomeKit camera would be preferable for sure. Ring are going to be shipping one soon with built in floodlights.

**Comment by jocamero** [comment]
Hello, I'm wondering if any additional functionality other than a motion sensor is supported.  I have that working, but was hoping for a video stream.  Is this possible?  Thanks.  (using Ring Pro)

**Comment by kieranmjones** [comment]
There is a programmable switch doorbell button as well but this isn't exposed in the Home app, some third party apps do show it though. The video stream isn't there right now though. 

Your Ring Pro already supports HomeKit natively without this homebridge plugin surely?

**Comment by jocamero** [comment]
Thanks for the clarification.

No, unfortunately the Ring Pro doesn't support HomeKit yet which is why I was trying to get it to work via homebridge.

> There is a programmable switch doorbell button as well but this isn't exposed in the Home app, some third party apps do show it though. The video stream isn't there right now though.

Your Ring Pro already supports HomeKit natively without this homebridge plugin surely?
