### ISSUE TITLE
ring stick up cams

### ISSUE THREAD

**Issue by thechrisreese** [homespun/homebridge-platform-ring-video-doorbell#8]
how would one add the stick up cams as another recognized motion device?

**Comment by mrose17** [comment]
i'm looking at https://github.com/homespun/homebridge-platform-ring-video-doorbell/pull/9 and i think it's a good start, but i suspect it will also break support for the doorbot. based on your PR, i am revising index.js to handle both cases (using a parameterized approach rather than a cut-and-paste approach. details in a bit.

**Comment by mrose17** [comment]
@thechrisreese - check out the current version 0.2.8 and see if it works for you... thanks!

**Comment by thechrisreese** [comment]
@mrose17 works perfectly. And now my automations are doing what I wanted.

**Comment by mrose17** [comment]
great!
